---
title: "DATA_316_Final_Project"
author: "Riley Fiske, Emily Liddell"
date: "2023-04-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}

life_data <- read.csv("https://raw.githubusercontent.com/rdfiske17/DATA316FinalProject/main/Datasets/life_expectancy_data.csv")

ggplot(data = life_data) +
  geom_jitter(aes(x = gdp_per_capita, y = life_expectancy, color = sex))

ggplot(data = life_data) +
  geom_jitter(aes(x = hdi, y = life_expectancy, color = sex))

ggplot(data = life_data) +
  geom_histogram(aes(x = population))

ggplot(data = life_data) +
  geom_histogram(aes(x = log(population)))

ggplot(data = life_data) +
  geom_jitter(aes(x = schooling_years, y = life_expectancy, color = sex))

ggplot(data = life_data) +
  geom_histogram(aes(x = ratio_below_povline))

ggplot(data = life_data) +
  geom_histogram(aes(x = log(ratio_below_povline)))

#now for countries

ggplot(data = life_data) +
  geom_point(aes(x = life_expectancy, y = fct_reorder(country,life_expectancy), color = sex))

ggplot(data = life_data) +
  geom_point(aes(x = gdp_per_capita, y = fct_reorder(country,gdp_per_capita)))

ggplot(data = life_data) +
  geom_point(aes(x = ratio_below_povline, y = fct_reorder(country,-ratio_below_povline)))

```


```{r}

mod.1 <- lm(life_expectancy ~ -1 + gdp_per_capita + hdi + population + ratio_below_povline + schooling_years + as.factor(sex), data = life_data)
summary(mod.1)

mod.2 <- lm(life_expectancy ~ -1 + gdp_per_capita + hdi + population + ratio_below_povline + schooling_years, data = life_data)
summary(mod.2)

mod.3 <- lm(life_expectancy ~ -1 + gdp_per_capita + population + ratio_below_povline + schooling_years + as.factor(sex), data = life_data)
summary(mod.3)

mod.4 <- lm(life_expectancy ~ -1 + gdp_per_capita + ratio_below_povline + schooling_years + as.factor(sex), data = life_data)
summary(mod.4)

mod.5 <- lm(life_expectancy ~ -1 + gdp_per_capita + log(ratio_below_povline + .01) + schooling_years + as.factor(sex), data = life_data)
summary(mod.5)

```

```{r}

beta5 <- coef(mod.5)

```


```{r}

life_data$pred.5 <- predict(mod.5)
life_data$resid.5 <- life_data$life_expectancy - life_data$pred.5
sigma <- sigma(mod.5)

ggplot(life_data, aes(x=pred.5, y=resid.5)) +
  geom_point() +
  geom_hline(yintercept=0, color = "red") +
  geom_hline(yintercept= c(sigma, -sigma), color="red", linetype="dashed") +
  labs(title= "Predicted Life Expectancy vs. Residuals",x = "Predicted Life Expectancy", y = "Residuals")

```

