---
title: "DATA 316 Final Project"
author: "Emily Liddell and Riley Fiske"
date: "2023-04-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
```

#Read in csv
```{r}
life_expectancy <- read.csv("https://raw.githubusercontent.com/rdfiske17/DATA316FinalProject/main/Datasets/life_expectancy_data.csv")
```

#Visualize the data
```{r}
ggplot(life_expectancy, aes(x = gdp_per_capita, y = life_expectancy)) +
  geom_jitter(aes(color = sex))

ggplot(life_expectancy, aes(x = log(population), y = life_expectancy)) +
  geom_jitter(aes(color = sex))

ggplot(life_expectancy, aes(x = hdi, y = life_expectancy)) +
  geom_jitter(aes(color = sex))

ggplot(life_expectancy, aes(x = log(ratio_below_povline), y = life_expectancy)) +
  geom_jitter(aes(color = sex))

ggplot(life_expectancy, aes(x = schooling_years, y = life_expectancy)) +
  geom_jitter(aes(color = sex))
```
#Create the model
```{r}
life.expectancy.model <- lm(life_expectancy ~ -1 + gdp_per_capita + log(ratio_below_povline + 0.01) + schooling_years + as.factor(sex), data = life_expectancy)
summary(life.expectancy.model)
```
#Visualize the model
```{r}
#Set up functions for the linear lines with male and female versions and everthing held constant except the variable of interest.
GDPlineF <- function(x){coef(life.expectancy.model)[1]*x + coef(life.expectancy.model)[2]*mean(log(life_expectancy$ratio_below_povline+0.01)) + coef(life.expectancy.model)[3]*mean(life_expectancy$schooling_years) + coef(life.expectancy.model)[4]}

GDPlineM <- function(x){coef(life.expectancy.model)[1]*x + coef(life.expectancy.model)[2]*mean(log(life_expectancy$ratio_below_povline+0.01)) + coef(life.expectancy.model)[3]*mean(life_expectancy$schooling_years) + coef(life.expectancy.model)[5]}

ratiolineF <- function(x){coef(life.expectancy.model)[1]*mean(life_expectancy$gdp_per_capita) + coef(life.expectancy.model)[2]*x + coef(life.expectancy.model)[3]*mean(life_expectancy$schooling_years) + coef(life.expectancy.model)[4]}

ratiolineM <- function(x){coef(life.expectancy.model)[1]*mean(life_expectancy$gdp_per_capita) + coef(life.expectancy.model)[2]*x + coef(life.expectancy.model)[3]*mean(life_expectancy$schooling_years) + coef(life.expectancy.model)[5]}

schoollineF <- function(x){coef(life.expectancy.model)[1]*mean(life_expectancy$gdp_per_capita) + coef(life.expectancy.model)[2]*mean(log(life_expectancy$ratio_below_povline+0.01)) + coef(life.expectancy.model)[3]*x + coef(life.expectancy.model)[4]}

schoollineM <- function(x){coef(life.expectancy.model)[1]*mean(life_expectancy$gdp_per_capita) + coef(life.expectancy.model)[2]*mean(log(life_expectancy$ratio_below_povline+0.01)) + coef(life.expectancy.model)[3]*x + coef(life.expectancy.model)[5]}

#Visualize the lines with the data
ggplot(life_expectancy, aes(x = gdp_per_capita, y = life_expectancy)) +
  geom_jitter(aes(color = sex)) +
  geom_function(fun = GDPlineF, aes(color = "Female")) +
  geom_function(fun = GDPlineM, aes(color = "Male"))

ggplot(life_expectancy, aes(x = log(ratio_below_povline), y = life_expectancy)) +
  geom_jitter(aes(color = sex)) +
  geom_function(fun = ratiolineF, aes(color = "Female")) +
  geom_function(fun = ratiolineM, aes(color = "Male"))

ggplot(life_expectancy, aes(x = schooling_years, y = life_expectancy)) +
  geom_jitter(aes(color = sex)) +
  geom_function(fun = schoollineF, aes(color = "Female")) +
  geom_function(fun = schoollineM, aes(color = "Male"))

#Grap of the prediction vs the actual life expectancy
life_expectancy$pred.1 <- predict(life.expectancy.model)

ggplot(life_expectancy, aes(x = life_expectancy, y =pred.1)) +
  geom_jitter() +
  geom_abline()
```
